### ISSUE TITLE
QuickDialog Not Working

### ISSUE THREAD

**Issue by deluakin** [billkainkoom/ogya#2]
Hi Bill,

Thanks for this awesome library. However, am having issue using the QuickDialog from the ogya:0.53 library.

Sample code
```
implementation 'com.github.billkainkoom:ogya:0.53'

import com.billkainkoom.ogya.quickdialog.QuickDialog
import com.billkainkoom.ogya.quickdialog.QuickDialogType
....

QuickDialog(
                context = this,
                style = QuickDialogType.Progress,
                title = "Please wait",
                message = "Confirmation code is being sent")
                .show()

```

[Caused by: kotlin.KotlinNullPointerException
        at com.billkainkoom.ogya.quickdialog.QuickDialog.initialize(QuickDialog.kt:55)
        at com.billkainkoom.ogya.quickdialog.QuickDialog.<init>(QuickDialog.kt:43)
        at com.billkainkoom.ogya.quickdialog.QuickDialog.<init>(QuickDialog.kt:288)](url)

But QuickDialog works perfectly fine when using the quickdialog:v0.70 library instead

```
implementation 'com.github.billkainkoom:quickdialog:v0.70'

import com.billkainkoom.quickdialog.QuickDialog
import com.billkainkoom.quickdialog.QuickDialogType
....

QuickDialog(
                context = this,
                style = QuickDialogType.Progress,
                title = "Please wait",
                message = "Confirmation code is being sent")
                .show()

```

**Comment by billkainkoom** [comment]
Hi Delu, please could you check the Context being passed (An application or service context will not be enough to show a dialog). I just tried quickDialog from ogya:0.53 and it seems to be working fine. 

 QuickDialog(
                context = context,
                style = QuickDialogType.Progress,
                title = "Please wait",
                message = "Walking round the world")
                .show()

<img width="272" alt="screen shot 2018-08-08 at 12 25 00 pm" src="https://user-images.githubusercontent.com/7753888/43836823-1e761944-9b06-11e8-8285-0adcf0a3069e.png">
